### ISSUE TITLE
No Boot Into Recovery

### ISSUE THREAD

**Issue by netshare-debug** [moosethegoose2213/automator-for-barrykn-micropatcher#15]
hello,
having performed successfully the installation of big sur 11.2.3 onto a cMP 5.1 with a metal capable nvidia geforce gtx 680.
what is now not possible anymore ist the boot into internal recovery partition (cmd + r). with each try it is performing an endless reboot until release. zap the pram did also not help out.

setup steps to big sure were the following: 
1. installation of catalina with the most actual patcher from dosdude1 (-> internal boot to recovery worked)
2. installation of big sur 11.2.3 with the must actual patcher from micropatcher (automator), v2.0 (-> no internal boot to recovery possible, although partition ist present and visible via diskutil list, csrutil is disabled, nvram no compat check is in).

what is missing? 
any targeting advices are welcome.
regards,
netshare

**Comment by minh-ton** [comment]
Hi there!

Firstly, it is not possible to boot into the internal Recovery partition with any patchers available, because the Recovery partition needs a new patch to bypass the compatibility check in order to boot into it. Dosdude1's Catalina patcher did included a patch for the Recovery partition; however, it is deprecated and no longer works for Big Sur.

Secondly, please keep your installer USB. The USB will acts as your Recovery partition, and you'll need it to re-patch your Mac if a problem occurs.
