### ISSUE TITLE
Post-Automator Failure

### ISSUE THREAD

**Issue by ms1963** [moosethegoose2213/automator-for-barrykn-micropatcher#16]
I installed Big Sur using the Automator. Everything worked fine until I finally booted to USB and selected Post-Automator in Utilities. It failed with the following message:

Macintosh HD
running 11.2.3 detected
/System/Applications/PostAutomator.app/Contents/Resources/postautomator.sh: line 17: dirname: command not found
[Out] Recovery mode detected!
/Volumes/Image Volume
If you can read this, that means that I probably broke something ...

I am using a Late 2013 iMac where I replaced the 3 TB fusion drive by a 2 TB SSD drive.

Interestingly, when I am using the installed Big Sur 11.2.3 everything works fine and seamlessly. I did not experience any problems so far when playing around with the system.

But, to be honest, I am not sure what could be missing due to the failure of the Post-Automator.

**Comment by moosethegoose2213** [comment]
This is a known issue. The dirname error is to be expected, as its involved in the way for checking if it is being ran in a recovery environment or not. That model of iMac does not need any post-install patches, so it does not affect usable in any way with failed patches. Will be fixed in next release!
